<?php

namespace AppBundle\Repository;

/**
 * docsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class docsRepository extends \Doctrine\ORM\EntityRepository
{
}
