<?php

namespace AppBundle\Repository;

/**
 * PodcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodcastRepository extends \Doctrine\ORM\EntityRepository
{
}
