<?php

namespace AppBundle\Repository;

/**
 * postTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
